@HostAddress = https://localhost:7225
@token = JWT

# Login to get JWT
POST {{HostAddress}}/jwt/login/
Content-Type: application/json

{
    "name": "user",
    "key": "key"
}

###
# decode JWT
GET {{HostAddress}}/jwt/decode-header/
Content-Type: application/json
Authorization: Bearer {{token}}

###
# decode JWT
GET {{HostAddress}}/jwt/decode-payload/
Content-Type: application/json
Authorization: Bearer {{token}}

###
# every user who has valid JWT can access this endpoint

GET {{HostAddress}}/jwt/role/
Content-Type: application/json
Authorization: Bearer {{token}}

###
# need admin role to access this endpoint

GET {{HostAddress}}/jwt/claims/
Content-Type: application/json
Authorization: Bearer {{token}}
